import { ZipArchive } from "archiver";
import type { Response } from "express";
import type { ContractProjectRow } from "@workspace/db";

function foundryToml(contractName: string): string {
  return `[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
solc_version = "0.8.24"

# Generated for "${contractName}" by AURA Forge.
# Docs: https://book.getfoundry.sh/
`;
}

function hardhatConfig(): string {
  return `require("@nomicfoundation/hardhat-toolbox");

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity: "0.8.24",
  networks: {
    // Fill in your RPC URL + private key to deploy, e.g. via a .env file:
    // sepolia: { url: process.env.RPC_URL, accounts: [process.env.PRIVATE_KEY] },
  },
};
`;
}

function evmDeployScript(contractName: string): string {
  return `// Deploy script (Hardhat). Run with: npx hardhat run scripts/deploy.js --network <network>
async function main() {
  const Factory = await ethers.getContractFactory("${contractName}");
  const contract = await Factory.deploy();
  await contract.waitForDeployment();
  console.log("${contractName} deployed to:", await contract.getAddress());
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
`;
}

function evmPackageJson(contractName: string): string {
  return JSON.stringify(
    {
      name: contractName.toLowerCase(),
      version: "1.0.0",
      private: true,
      scripts: {
        build: "npx hardhat compile",
        test: "npx hardhat test",
        deploy: "npx hardhat run scripts/deploy.js",
      },
      devDependencies: {
        hardhat: "^2.22.0",
        "@nomicfoundation/hardhat-toolbox": "^5.0.0",
      },
    },
    null,
    2,
  );
}

function anchorToml(contractName: string): string {
  const programId = "11111111111111111111111111111111";
  const snakeCase = contractName
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toLowerCase();
  return `[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
${snakeCase} = "${programId}"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
`;
}

function solanaPackageJson(contractName: string): string {
  return JSON.stringify(
    {
      name: contractName.toLowerCase(),
      version: "1.0.0",
      private: true,
      scripts: {
        build: "anchor build",
        test: "anchor test",
        deploy: "anchor deploy",
      },
      devDependencies: {
        "@coral-xyz/anchor": "^0.30.0",
        "ts-mocha": "^10.0.0",
      },
    },
    null,
    2,
  );
}

function solanaDeployScript(): string {
  return `#!/usr/bin/env bash
# Deploy script (Anchor). Run: ./scripts/deploy.sh <cluster>
set -e
CLUSTER="\${1:-devnet}"
anchor deploy --provider.cluster "$CLUSTER"
`;
}

function readme(project: ContractProjectRow): string {
  const isEvm = project.ecosystem === "EVM";
  return `# ${project.contractName}

Generated by AURA Forge${project.templateId ? ` from the "${project.templateId}" template` : ""}${
    project.upgradeable ? " (UUPS upgradeable pattern)" : ""
  }.

Prompt used: ${project.prompt}

Last recorded security score: ${project.securityScore ?? "N/A"}/100${
    project.securityNotes ? `\n> ${project.securityNotes}` : ""
  }
${project.gasNotes ? `\nGas & efficiency notes: ${project.gasNotes}\n` : ""}

## Setup

${
  isEvm
    ? `This project uses [Hardhat](https://hardhat.org/).

\`\`\`bash
npm install
npm run build   # compile with solc
npm test        # run the generated test suite
npm run deploy  # deploy using scripts/deploy.js (configure your network in hardhat.config.js first)
\`\`\`

A minimal \`foundry.toml\` is also included if you prefer [Foundry](https://book.getfoundry.sh/) instead:

\`\`\`bash
forge build
forge test
\`\`\``
    : `This project uses [Anchor](https://www.anchor-lang.com/).

\`\`\`bash
yarn install
anchor build      # compile the program
anchor test       # run the generated test suite
./scripts/deploy.sh devnet   # deploy to a cluster
\`\`\`

${
  project.compiledBytecode
    ? "Note: this program was already compiled in the AURA Forge environment via a real cargo-build-sbf/Anchor toolchain — the compiled `.so` and IDL in this export come from that real build. Running `anchor build` here recompiles it locally."
    : "Note: this program's source and IDL were generated but could not be compiled in the AURA Forge environment (the Anchor/cargo toolchain was unavailable there) — `anchor build` here is the first real compile."
}`
}

## Files

- \`${isEvm ? "src/" : "programs/" + project.contractName.toLowerCase() + "/src/lib.rs"}\` — the generated contract source.
- \`${isEvm ? "test/" : "tests/"}\` — the generated test suite${project.testSuiteCode ? "" : " (not generated for this project)"}.
- \`${isEvm ? "hardhat.config.js / foundry.toml" : "Anchor.toml"}\` — standard toolchain config.
- \`${isEvm ? "scripts/deploy.js" : "scripts/deploy.sh"}\` — a minimal deploy script.

This archive does not run the build/test/deploy for you — use the commands above locally.
`;
}

/**
 * Streams a zip archive containing the contract source, generated tests (if
 * any), ecosystem-standard toolchain boilerplate, a deploy script, and a
 * README directly to the HTTP response.
 */
export function streamProjectExport(project: ContractProjectRow, res: Response): void {
  const isEvm = project.ecosystem === "EVM";
  const fileSafeName = project.contractName.replace(/[^a-zA-Z0-9_-]/g, "") || "Contract";

  res.setHeader("Content-Type", "application/zip");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="${fileSafeName.toLowerCase()}-export.zip"`,
  );

  const archive = new ZipArchive({ zlib: { level: 9 } });
  archive.on("error", (err: Error) => {
    // Headers are already sent by the time archiver streams data, so just
    // terminate the response; there's no clean way to send a JSON error here.
    res.destroy(err);
  });
  archive.pipe(res);

  archive.append(readme(project), { name: "README.md" });

  if (isEvm) {
    archive.append(project.smartContractCode ?? "", { name: `src/${fileSafeName}.sol` });
    if (project.testSuiteCode) {
      archive.append(project.testSuiteCode, { name: `test/${fileSafeName}.t.sol` });
    }
    archive.append(hardhatConfig(), { name: "hardhat.config.js" });
    archive.append(foundryToml(project.contractName), { name: "foundry.toml" });
    archive.append(evmPackageJson(project.contractName), { name: "package.json" });
    archive.append(evmDeployScript(project.contractName), { name: "scripts/deploy.js" });
    if (project.abiOrIdl) {
      archive.append(project.abiOrIdl, { name: `abi/${fileSafeName}.abi.json` });
    }
  } else {
    const programDir = `programs/${fileSafeName.toLowerCase()}/src`;
    archive.append(project.smartContractCode ?? "", { name: `${programDir}/lib.rs` });
    if (project.testSuiteCode) {
      archive.append(project.testSuiteCode, { name: `tests/${fileSafeName.toLowerCase()}.ts` });
    }
    archive.append(anchorToml(project.contractName), { name: "Anchor.toml" });
    archive.append(solanaPackageJson(project.contractName), { name: "package.json" });
    archive.append(solanaDeployScript(), { name: "scripts/deploy.sh" });
    if (project.abiOrIdl) {
      archive.append(project.abiOrIdl, { name: `idl/${fileSafeName.toLowerCase()}.json` });
    }
  }

  archive.finalize();
}
