import { motion } from 'framer-motion';
import Navbar from '../components/layout/Navbar';
import Footer from '../components/layout/Footer';

export default function Terms() {
  return (
    <div className="min-h-[100dvh] flex flex-col bg-background text-foreground selection:bg-primary/20">
      <Navbar />
      
      <main className="flex-1 flex flex-col pt-32 pb-24 px-6 relative">
        <div className="container mx-auto max-w-3xl relative z-10">
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mb-12"
          >
            <h1 className="text-4xl font-mono font-bold text-white mb-4">Terms of Service</h1>
            <p className="text-muted-foreground">Effective Date: July 2026</p>
          </motion.div>

          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="prose prose-invert prose-p:text-muted-foreground prose-headings:font-mono prose-headings:text-white max-w-none"
          >
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using AURA Forge, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use our services.
            </p>

            <h2>2. Description of Service</h2>
            <p>
              AURA Forge is an AI-powered smart contract generation and auditing platform. It includes a Web App, CLI, and Model Context Protocol (MCP) server.
            </p>

            <h2>3. User Accounts</h2>
            <p>
              You are responsible for safeguarding your account credentials and API keys. You agree to notify us immediately of any unauthorized use of your account.
            </p>

            <h2>4. Acceptable Use</h2>
            <p>You agree NOT to use AURA Forge to:</p>
            <ul>
              <li>Evade international sanctions or laws.</li>
              <li>Intentionally generate malicious contracts designed to exploit protocols or steal funds.</li>
              <li>Abuse, spam, or excessively load our API beyond established rate limits.</li>
            </ul>

            <h2>5. Intellectual Property</h2>
            <p>
              <strong>Your Code:</strong> You own the intellectual property rights to the smart contracts generated based on your prompts.
              <br />
              <strong>Our Platform:</strong> AURA Forge retains all rights to the platform, logos, algorithms, and generation pipeline methodologies.
            </p>

            <h2>6. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE AND GENERATED CODE ARE PROVIDED "AS IS". WE MAKE NO WARRANTIES, EXPRESS OR IMPLIED, THAT THE GENERATED SMART CONTRACTS ARE FREE FROM VULNERABILITIES, BUGS, OR LOGIC FLAWS. YOU MUST AUDIT ALL CODE BEFORE DEPLOYING IT TO PRODUCTION NETWORKS.
            </p>

            <h2>7. Limitation of Liability</h2>
            <p>
              AURA Forge shall not be liable for any financial losses, hacks, exploits, or damages resulting from the use of code generated by our platform. Your use of the generated code is entirely at your own risk.
            </p>

            <h2>8. Indemnification</h2>
            <p>
              You agree to indemnify and hold AURA Forge harmless from any claims, damages, or expenses arising from your use of the service or deployment of the generated contracts.
            </p>

            <h2>9. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account at any time if you violate these terms.
            </p>

            <h2>10. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of Delaware, USA, without regard to its conflict of law principles.
            </p>

            <h2>11. Contact</h2>
            <p>
              If you have any questions about these Terms, please contact us at: <a href="mailto:invest@auraforge.io" className="text-primary hover:underline">invest@auraforge.io</a>.
            </p>
          </motion.div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
}